<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUqmwk4n\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUqmwk4n/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUqmwk4n.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUqmwk4n\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUqmwk4n\appProdProjectContainer([
    'container.build_hash' => 'Uqmwk4n',
    'container.build_id' => 'c7f2e951',
    'container.build_time' => 1631105267,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUqmwk4n');
